// 연습 문장 은행 — 레벨 × 카테고리
// beginner: 초등 수준(짧은 문장·기초 파닉스), intermediate: 중등 일상회화, advanced: 성인·전문
// 주의: 기존 문장의 텍스트는 수정 금지 — 연습 기록(ec_done)이 문장 텍스트를 키로 사용
const SENTENCES_BY_LEVEL = {
  beginner: {
    daily: [
      { text: "Hi! Nice to meet you." },
      { text: "I like pizza and fried chicken." },
      { text: "Can I have some water, please?" },
      { text: "What time is it now?" },
      { text: "I go to school at eight thirty." },
      { text: "My favorite subject is P.E." },
      { text: "Can you help me with my homework?" },
      { text: "I played games with my brother yesterday." },
      { text: "It's sunny and warm today." },
      { text: "I want to be a scientist someday." },
      { text: "How much is this ice cream?" },
      { text: "See you tomorrow at school!" },
      { text: "My name is Minjun. What's your name?" },
      { text: "I have two sisters and one brother." },
      { text: "This is my best friend, Jiho." },
      { text: "I'm ten years old. How old are you?" },
      { text: "Do you like soccer or basketball?" },
      { text: "Let's play together after school." },
      { text: "I'm hungry. Let's eat lunch." },
      { text: "What's your favorite color? Mine is blue." },
      { text: "I can swim, but I can't dive." },
      { text: "Where is the bathroom, please?" },
      { text: "It's raining. Don't forget your umbrella." },
      { text: "I brush my teeth before I go to bed." },
      { text: "My dog is small and very cute." },
      { text: "Can I borrow your pencil, please?" },
      { text: "I'm sorry. It was my mistake." },
      { text: "Thank you so much for your help." },
      { text: "What day is it today? It's Friday!" },
      { text: "I watched a funny movie last night." },
      { text: "My mom makes the best food in the world." },
      { text: "I want a hamburger and orange juice, please." },
      { text: "Look! There's a rainbow in the sky." },
      { text: "I'm so excited about the field trip." },
      { text: "Please open your books to page ten." },
      { text: "He runs faster than me." },
      { text: "Winter is coming. I love making snowmen." },
      { text: "May I go to the restroom, teacher?" },
      { text: "We have an English test next Monday." },
      { text: "I lost my eraser. Have you seen it?" },
      { text: "Happy birthday! This present is for you." },
      { text: "Let's meet at the playground at three." },
      { text: "I feel sick. I have a headache." },
      { text: "Good night, Mom. See you in the morning." },
    ],
    drill: [
      { text: "I like rice and fried rice.", tip: "r /r/ — 혀를 안쪽으로 말고 입천장에 닿지 않게" },
      { text: "Look at the little lake.", tip: "l /l/ — 혀끝을 윗니 뒤에 붙이기" },
      { text: "Think about three things.", tip: "th /θ/ — 혀끝을 이 사이에" },
      { text: "This is my mother and father.", tip: "th /ð/ — 유성음 th" },
      { text: "Five fish swim very fast.", tip: "f /f/ — 윗니로 아랫입술 살짝 물기" },
      { text: "A big pig is eating a peach.", tip: "p/b 구분" },
      { text: "She sells six small shells.", tip: "s/ʃ 구분" },
      { text: "We watch a movie on Wednesday.", tip: "w /w/ — 입술 둥글게" },
      { text: "The zebra is at the zoo.", tip: "z /z/ — 유성음 s" },
      { text: "A ship and a sheep. Sit on the seat.", tip: "i/ɪ 모음 구분 (ship/sheep)" },
      { text: "Red lorry, yellow lorry.", tip: "r/l 교차 연습" },
      { text: "The little lion licked the yellow lolly.", tip: "l /l/ — 혀끝을 윗니 뒤에" },
      { text: "Three thin thieves thought a thought.", tip: "th /θ/ 연속" },
      { text: "That brother bathes in the bathtub.", tip: "th /ð/ — 유성음 th" },
      { text: "Fred fried four fresh fish for father.", tip: "f/fr — 윗니로 아랫입술" },
      { text: "Vivid violet vans move very fast.", tip: "v /v/ — 유성음 f" },
      { text: "Pat put a pretty puppy in the park.", tip: "p /p/ — 강한 파열음" },
      { text: "Bob bought a big blue balloon.", tip: "b /b/ — 유성음 p" },
      { text: "Which witch watched the white whale?", tip: "w /w/ — 입술 둥글게" },
      { text: "Silly Sally sings a simple song.", tip: "s /s/ 연속" },
      { text: "Shy sheep should share the shiny shell.", tip: "ʃ 연속 (sh)" },
      { text: "The zebra zig-zagged through the zoo.", tip: "z /z/ — 벌이 나는 소리처럼" },
      { text: "Cheap chicken chips and chunky cheese.", tip: "tʃ 발음 (ch)" },
      { text: "George the giant jumped with joy.", tip: "dʒ 발음 (j/g)" },
      { text: "Green grapes grow in Grandma's garden.", tip: "gr 연속 자음" },
      { text: "Clean clothes climb the clear cliff.", tip: "cl 연속 자음" },
      { text: "A fat cat sat on a flat mat.", tip: "æ 모음 (cat)" },
      { text: "Hot coffee in a copper coffee pot.", tip: "ɑ/ɔ 모음" },
      { text: "Good books look good on wooden hooks.", tip: "ʊ 모음 (book)" },
      { text: "The bird heard the early worker.", tip: "ɜːr 모음 (bird)" },
    ],
  },
  intermediate: {
    daily: [
      { text: "What do you usually do on weekends?" },
      { text: "I'm looking forward to the school festival." },
      { text: "Could you say that again more slowly?" },
      { text: "I have to finish my homework before dinner." },
      { text: "How about meeting in front of the library?" },
      { text: "I've never tried Indian food before." },
      { text: "The math test was harder than I expected." },
      { text: "Do you know what time the movie starts?" },
      { text: "I'm saving money to buy a new phone." },
      { text: "If it rains tomorrow, let's stay home and watch a movie." },
      { text: "My favorite singer is releasing a new album this week." },
      { text: "Thanks for helping me with my English homework." },
      { text: "Can you recommend a good book for someone my age?" },
      { text: "I'm thinking about joining the school band this year." },
      { text: "It's been raining all week, and I'm sick of it." },
      { text: "Would it be okay if I brought a friend along?" },
      { text: "I stayed up too late studying for the science quiz." },
      { text: "How long does it take to get there by bus?" },
      { text: "I'm really into K-pop these days. What about you?" },
      { text: "Sorry I'm late. I missed the first bus." },
      { text: "Let me check my schedule and get back to you." },
      { text: "The new student in our class is really good at math." },
      { text: "I can't decide between the blue one and the black one." },
      { text: "We should practice more if we want to win the game." },
      { text: "My phone battery died right in the middle of the game." },
      { text: "Have you finished the group project for history class?" },
      { text: "I'd love to, but I have an academy class tonight." },
      { text: "What kind of music do you listen to when you study?" },
      { text: "I promised my mom I'd be home before nine." },
      { text: "That restaurant is always crowded on weekends." },
      { text: "I'm trying to save up for a concert ticket." },
      { text: "Could you explain that part again? I got lost." },
      { text: "It turns out the test was easier than everyone said." },
      { text: "Do you prefer studying alone or with friends?" },
      { text: "I left my homework at home. Can I turn it in tomorrow?" },
      { text: "The weather forecast says it'll clear up by the afternoon." },
      { text: "I've been learning English for five years, but speaking is still hard." },
      { text: "Why don't we split the bill this time?" },
      { text: "My little brother keeps borrowing my stuff without asking." },
      { text: "I'm nervous about the presentation in front of the whole class." },
      { text: "You should have seen the look on his face!" },
      { text: "Let's take a group photo before everyone leaves." },
      { text: "I didn't mean to hurt your feelings. I apologize." },
      { text: "If we hurry, we can still catch the earlier train." },
    ],
    drill: [
      { text: "I think this thing is thinner than that one.", tip: "th /θ/ — 혀끝을 이 사이에" },
      { text: "They gathered together with their brothers.", tip: "th /ð/ — 유성음 th" },
      { text: "The red lorry rolled along the road.", tip: "r 연속 발음" },
      { text: "Please believe me, the library is really large.", tip: "r/l 혼합 구분" },
      { text: "Everybody loves the very vivid video.", tip: "v /v/ — 아랫입술을 살짝 물기" },
      { text: "Fresh fruit is very good for your body.", tip: "f/v 구분" },
      { text: "Whether the weather is warm or wet, we walk.", tip: "w /w/ — 입술 둥글게" },
      { text: "She should share those shiny shoes.", tip: "s/ʃ 구분" },
      { text: "The busy bees buzz in the breeze.", tip: "z /z/ — 유성음 s" },
      { text: "Would you pull the full bowl from the pool?", tip: "u/ʊ 모음 구분" },
      { text: "The sheep on the ship keep sleeping.", tip: "i/ɪ 모음 구분" },
      { text: "George enjoys orange juice and jelly.", tip: "dʒ 발음" },
      { text: "Thirty-three thirsty thinkers thanked the thoughtful teacher.", tip: "th /θ/ 고강도" },
      { text: "Those brothers would rather gather leather together.", tip: "th /ð/ 고강도" },
      { text: "The friendly frog leaped from the fragrant flower.", tip: "fr/fl 연속 자음" },
      { text: "Larry really relied on Laura's rural railway.", tip: "r/l 고강도 혼합" },
      { text: "Eleven benevolent elephants delivered valuable vegetables.", tip: "v/l 혼합" },
      { text: "She showed Sasha the special seashell collection.", tip: "s/ʃ 혼합" },
      { text: "Choose the cheese and chew it cheerfully.", tip: "tʃ 연속" },
      { text: "The general genuinely enjoyed the gigantic journey.", tip: "dʒ 연속" },
      { text: "Peter picked a proper paper for the report.", tip: "p 파열음 연속" },
      { text: "The weary warrior wandered westward in the wind.", tip: "w 연속" },
      { text: "Yellow yogurt and unique yoga in New York.", tip: "j /j/ 발음 (y)" },
      { text: "The zealous musician amazed the puzzled audience.", tip: "z 혼합" },
      { text: "Bad bed, bat bet — say them differently.", tip: "æ/e 모음 구분" },
      { text: "The hurt bird returned to the third perch early.", tip: "ɜːr 모음 연속" },
      { text: "Walk along the tall wall, but don't fall.", tip: "ɔː 모음 연속" },
      { text: "The cook took a good look at the cookbook.", tip: "ʊ 모음 연속" },
      { text: "Beat it, bit it — feel the difference.", tip: "iː/ɪ 모음 구분" },
      { text: "The proud crowd found the round fountain downtown.", tip: "aʊ 이중모음" },
    ],
  },
  advanced: {
    daily: [
      { text: "Could you tell me how to get to the nearest subway station?" },
      { text: "I've been meaning to try that new restaurant downtown." },
      { text: "Sorry, I didn't quite catch that. Could you say it again?" },
      { text: "It took me a while to get used to the weather here." },
      { text: "Would you mind if I opened the window a little?" },
      { text: "I'm not sure yet, but I'll let you know by tomorrow." },
      { text: "That sounds great. Let's grab a coffee sometime this week." },
      { text: "I usually go for a walk after dinner to clear my head." },
      { text: "Honestly, I think it's worth the price considering the quality." },
      { text: "We ended up staying much longer than we had planned." },
      { text: "Could you give me a hand with this? It's heavier than it looks." },
      { text: "I'd rather stay in tonight and catch up on some reading." },
      { text: "I'll have to double-check my calendar before I commit to that." },
      { text: "To be honest, the movie didn't live up to the hype." },
      { text: "Could we push our meeting back by half an hour?" },
      { text: "I ran into an old colleague at the conference last week." },
      { text: "It's a bit of a long shot, but it's worth trying." },
      { text: "Let me play devil's advocate for a moment here." },
      { text: "I couldn't agree more with what you just said." },
      { text: "We might as well make the most of the situation." },
      { text: "The traffic was terrible, so I barely made it on time." },
      { text: "I've been putting off the paperwork all week, unfortunately." },
      { text: "Feel free to reach out if anything comes up." },
      { text: "That's a fair point, but I see it a little differently." },
      { text: "The renovation ended up costing twice as much as we expected." },
      { text: "I'd appreciate it if you could keep me in the loop." },
      { text: "Off the top of my head, I'd say about twenty percent." },
      { text: "We should probably wrap things up — it's getting late." },
      { text: "The jet lag hit me much harder than I anticipated." },
      { text: "I'm on the fence about whether to accept the offer." },
      { text: "Things have been hectic at work since the reorganization." },
      { text: "Let's touch base early next week to finalize the details." },
      { text: "It slipped my mind completely — I owe you an apology." },
      { text: "The view from the hotel room was absolutely breathtaking." },
      { text: "I figured it would be quicker to walk than to drive." },
      { text: "You might want to take that review with a grain of salt." },
      { text: "We got caught in the rain without an umbrella, of course." },
      { text: "I'm still weighing the pros and cons of each option." },
      { text: "The presentation went smoothly, all things considered." },
      { text: "Would you happen to know a good dentist around here?" },
      { text: "I try to squeeze in a workout before breakfast when I can." },
      { text: "The deadline is tight, but I think we can pull it off." },
      { text: "It took forever to get through customs at the airport." },
      { text: "Now that you mention it, I did notice something odd." },
    ],
    medical: [
      { text: "The patient's hemoglobin level has dropped significantly since admission." },
      { text: "We need to rule out contamination before reporting this blood culture result." },
      { text: "The delta check flagged this potassium value as potentially spurious." },
      { text: "Thank you for the opportunity to present our findings today." },
      { text: "Our data suggest that the new assay improves diagnostic accuracy." },
      { text: "Could you elaborate on how you validated the reference intervals?" },
      { text: "The specimen was hemolyzed, so we requested a redraw." },
      { text: "This figure shows the correlation between the two measurement methods." },
      { text: "In conclusion, early detection remains the key to better outcomes." },
      { text: "I'd be happy to take any questions from the audience." },
      { text: "The critical value was called to the attending physician immediately." },
      { text: "We suspect a wrong blood in tube error based on the delta check." },
      { text: "The prothrombin time is markedly prolonged; please verify the sample volume." },
      { text: "This discrepancy suggests preanalytical error rather than a true change." },
      { text: "The platelet clumping was confirmed on the peripheral blood smear." },
      { text: "We recommend repeating the test with a fresh specimen tomorrow morning." },
      { text: "The quality control results were outside two standard deviations today." },
      { text: "External proficiency testing confirmed the accuracy of our new analyzer." },
      { text: "The turnaround time for routine chemistry has improved significantly this quarter." },
      { text: "Please interpret the tumor marker trend with caution in this context." },
      { text: "The blood culture turned positive with gram-negative rods after twelve hours." },
      { text: "Antimicrobial susceptibility results will be available within forty-eight hours." },
      { text: "The reference interval differs by age and sex for this analyte." },
      { text: "Hemolysis can falsely elevate potassium and lactate dehydrogenase levels." },
      { text: "Our laboratory participates in the international standardization program." },
      { text: "The molecular assay detected a clinically significant mutation in this gene." },
      { text: "May I draw your attention to the second figure on this slide?" },
      { text: "This retrospective study included over ten thousand laboratory results." },
      { text: "The findings were statistically significant, with a p-value below 0.05." },
      { text: "We appreciate the reviewers' insightful comments on our manuscript." },
    ],
    drill: [
      { text: "I think this thing is thicker than that one.", tip: "th /θ/ — 혀끝을 이 사이에" },
      { text: "My mother and father gathered together on their birthday.", tip: "th /ð/ — 유성음 th" },
      { text: "The red lorry carried yellow jelly along the road.", tip: "r/l 구분" },
      { text: "I really love the rice, but I'd rather have the lice removed.", tip: "r/l 최소대립쌍" },
      { text: "Everybody believes the vivid video was very valuable.", tip: "v /v/ — 아랫입술을 살짝 물기" },
      { text: "Five brave friends viewed the beautiful violet flowers.", tip: "f/v vs b/p 구분" },
      { text: "We were wondering whether the weather would get worse.", tip: "w /w/ — 입술 둥글게" },
      { text: "She sells seashells by the seashore.", tip: "s/ʃ 구분" },
      { text: "The zoo's busy bees seized the frozen cheese.", tip: "z /z/ — 유성음 s" },
      { text: "Would you pull the full bowl of wool from the pool?", tip: "u/ʊ 모음 구분" },
      { text: "A big ship is leaving, but the sheep keep sleeping.", tip: "i/ɪ 모음 구분 (ship/sheep)" },
      { text: "The judge urged the gentle giant to change gradually.", tip: "dʒ 발음" },
      { text: "The sixth sick sheikh's sixth sheep is sick.", tip: "s/ʃ/θ 최고난도" },
      { text: "Rarely does the literal rule apply to rural literature.", tip: "r/l 최고난도" },
      { text: "Thirty-three thousand thoughtful theorists thoroughly analyzed the thesis.", tip: "θ 고강도 연속" },
      { text: "Whether they gather here or there, they breathe together.", tip: "ð 고강도 연속" },
      { text: "The vindictive villain vividly favored the velvet vest.", tip: "v 고강도" },
      { text: "Freshly fried flying fish, freshly fried flesh.", tip: "f/fl/fr 연속" },
      { text: "Which wristwatches are Swiss wristwatches?", tip: "w/r 혼합" },
      { text: "The judicious judge judged the joyful juggler gently.", tip: "dʒ 고강도" },
      { text: "Chester chose to cherish the champion's china chess set.", tip: "tʃ 고강도" },
      { text: "The zoologist's dizzy cousin seized the buzzing scissors.", tip: "z 고강도" },
      { text: "Peculiarly practical, the parallel plan properly prospered.", tip: "p/pl/pr 연속" },
      { text: "The bleak black block blocked the bright blue bloom.", tip: "bl 연속" },
      { text: "Steadily, the strict strategist strengthened the structure.", tip: "str 삼중 자음" },
      { text: "The world whirled while the squirrel twirled.", tip: "ɜːrl 최고난도 (world/girl)" },
      { text: "Full fool, pull pool — vowel length matters.", tip: "ʊ/uː 모음 구분" },
      { text: "We were weary of the weird, eerie atmosphere.", tip: "ɪər 이중모음" },
      { text: "Law, low, raw, row — round then release.", tip: "ɔː/oʊ 모음 구분" },
      { text: "Authorities thoroughly authorized the author's theory.", tip: "θ/ɔː 종합" },
    ],
  },
};

// 레벨 테스트 — 쉬운 문장 → 어려운 문장 순서로 6개 읽고 평균 점수로 배치
const LEVEL_TEST_SENTENCES = [
  { text: "I like apples and bananas." },
  { text: "She goes to school every day." },
  { text: "We played soccer with our friends yesterday." },
  { text: "Could you tell me how to get to the library?" },
  { text: "I think it's going to rain this afternoon, so take an umbrella." },
  { text: "If I had more time, I would travel around the world with my family." },
];

// 평균 총점 기준 레벨 배치
const LEVEL_THRESHOLDS = { advanced: 85, intermediate: 70 }; // 그 미만은 beginner

const CATEGORY_LABELS = {
  daily: "일상 회화",
  medical: "진료·학술",
  drill: "발음 집중훈련",
  review: "오답 복습",
  custom: "직접 입력",
};
