// 연습 문장 은행 — 레벨 × 카테고리
// beginner: 초등 수준(짧은 문장·기초 파닉스), intermediate: 중등 일상회화, advanced: 성인·전문
const SENTENCES_BY_LEVEL = {
  beginner: {
    daily: [
      { text: "Hi! Nice to meet you." },
      { text: "I like pizza and fried chicken." },
      { text: "Can I have some water, please?" },
      { text: "What time is it now?" },
      { text: "I go to school at eight thirty." },
      { text: "My favorite subject is P.E." },
      { text: "Can you help me with my homework?" },
      { text: "I played games with my brother yesterday." },
      { text: "It's sunny and warm today." },
      { text: "I want to be a scientist someday." },
      { text: "How much is this ice cream?" },
      { text: "See you tomorrow at school!" },
    ],
    drill: [
      { text: "I like rice and fried rice.", tip: "r /r/ — 혀를 안쪽으로 말고 입천장에 닿지 않게" },
      { text: "Look at the little lake.", tip: "l /l/ — 혀끝을 윗니 뒤에 붙이기" },
      { text: "Think about three things.", tip: "th /θ/ — 혀끝을 이 사이에" },
      { text: "This is my mother and father.", tip: "th /ð/ — 유성음 th" },
      { text: "Five fish swim very fast.", tip: "f /f/ — 윗니로 아랫입술 살짝 물기" },
      { text: "A big pig is eating a peach.", tip: "p/b 구분" },
      { text: "She sells six small shells.", tip: "s/ʃ 구분" },
      { text: "We watch a movie on Wednesday.", tip: "w /w/ — 입술 둥글게" },
      { text: "The zebra is at the zoo.", tip: "z /z/ — 유성음 s" },
      { text: "A ship and a sheep. Sit on the seat.", tip: "i/ɪ 모음 구분 (ship/sheep)" },
    ],
  },
  intermediate: {
    daily: [
      { text: "What do you usually do on weekends?" },
      { text: "I'm looking forward to the school festival." },
      { text: "Could you say that again more slowly?" },
      { text: "I have to finish my homework before dinner." },
      { text: "How about meeting in front of the library?" },
      { text: "I've never tried Indian food before." },
      { text: "The math test was harder than I expected." },
      { text: "Do you know what time the movie starts?" },
      { text: "I'm saving money to buy a new phone." },
      { text: "If it rains tomorrow, let's stay home and watch a movie." },
      { text: "My favorite singer is releasing a new album this week." },
      { text: "Thanks for helping me with my English homework." },
    ],
    drill: [
      { text: "I think this thing is thinner than that one.", tip: "th /θ/ — 혀끝을 이 사이에" },
      { text: "They gathered together with their brothers.", tip: "th /ð/ — 유성음 th" },
      { text: "The red lorry rolled along the road.", tip: "r 연속 발음" },
      { text: "Please believe me, the library is really large.", tip: "r/l 혼합 구분" },
      { text: "Everybody loves the very vivid video.", tip: "v /v/ — 아랫입술을 살짝 물기" },
      { text: "Fresh fruit is very good for your body.", tip: "f/v 구분" },
      { text: "Whether the weather is warm or wet, we walk.", tip: "w /w/ — 입술 둥글게" },
      { text: "She should share those shiny shoes.", tip: "s/ʃ 구분" },
      { text: "The busy bees buzz in the breeze.", tip: "z /z/ — 유성음 s" },
      { text: "Would you pull the full bowl from the pool?", tip: "u/ʊ 모음 구분" },
      { text: "The sheep on the ship keep sleeping.", tip: "i/ɪ 모음 구분" },
      { text: "George enjoys orange juice and jelly.", tip: "dʒ 발음" },
    ],
  },
  advanced: {
    daily: [
      { text: "Could you tell me how to get to the nearest subway station?" },
      { text: "I've been meaning to try that new restaurant downtown." },
      { text: "Sorry, I didn't quite catch that. Could you say it again?" },
      { text: "It took me a while to get used to the weather here." },
      { text: "Would you mind if I opened the window a little?" },
      { text: "I'm not sure yet, but I'll let you know by tomorrow." },
      { text: "That sounds great. Let's grab a coffee sometime this week." },
      { text: "I usually go for a walk after dinner to clear my head." },
      { text: "Honestly, I think it's worth the price considering the quality." },
      { text: "We ended up staying much longer than we had planned." },
      { text: "Could you give me a hand with this? It's heavier than it looks." },
      { text: "I'd rather stay in tonight and catch up on some reading." },
    ],
    medical: [
      { text: "The patient's hemoglobin level has dropped significantly since admission." },
      { text: "We need to rule out contamination before reporting this blood culture result." },
      { text: "The delta check flagged this potassium value as potentially spurious." },
      { text: "Thank you for the opportunity to present our findings today." },
      { text: "Our data suggest that the new assay improves diagnostic accuracy." },
      { text: "Could you elaborate on how you validated the reference intervals?" },
      { text: "The specimen was hemolyzed, so we requested a redraw." },
      { text: "This figure shows the correlation between the two measurement methods." },
      { text: "In conclusion, early detection remains the key to better outcomes." },
      { text: "I'd be happy to take any questions from the audience." },
    ],
    drill: [
      { text: "I think this thing is thicker than that one.", tip: "th /θ/ — 혀끝을 이 사이에" },
      { text: "My mother and father gathered together on their birthday.", tip: "th /ð/ — 유성음 th" },
      { text: "The red lorry carried yellow jelly along the road.", tip: "r/l 구분" },
      { text: "I really love the rice, but I'd rather have the lice removed.", tip: "r/l 최소대립쌍" },
      { text: "Everybody believes the vivid video was very valuable.", tip: "v /v/ — 아랫입술을 살짝 물기" },
      { text: "Five brave friends viewed the beautiful violet flowers.", tip: "f/v vs b/p 구분" },
      { text: "We were wondering whether the weather would get worse.", tip: "w /w/ — 입술 둥글게" },
      { text: "She sells seashells by the seashore.", tip: "s/ʃ 구분" },
      { text: "The zoo's busy bees seized the frozen cheese.", tip: "z /z/ — 유성음 s" },
      { text: "Would you pull the full bowl of wool from the pool?", tip: "u/ʊ 모음 구분" },
      { text: "A big ship is leaving, but the sheep keep sleeping.", tip: "i/ɪ 모음 구분 (ship/sheep)" },
      { text: "The judge urged the gentle giant to change gradually.", tip: "dʒ 발음" },
    ],
  },
};

// 레벨 테스트 — 쉬운 문장 → 어려운 문장 순서로 6개 읽고 평균 점수로 배치
const LEVEL_TEST_SENTENCES = [
  { text: "I like apples and bananas." },
  { text: "She goes to school every day." },
  { text: "We played soccer with our friends yesterday." },
  { text: "Could you tell me how to get to the library?" },
  { text: "I think it's going to rain this afternoon, so take an umbrella." },
  { text: "If I had more time, I would travel around the world with my family." },
];

// 평균 총점 기준 레벨 배치
const LEVEL_THRESHOLDS = { advanced: 85, intermediate: 70 }; // 그 미만은 beginner

const CATEGORY_LABELS = {
  daily: "일상 회화",
  medical: "진료·학술",
  drill: "발음 집중훈련",
  review: "오답 복습",
  custom: "직접 입력",
};
